import { getAsianLanguage } from "@/lib/i18n/languages"
import type { SupportedLanguage } from "@/types"

export type PdfLabels = {
  reportTitle: string
  farmer: string
  crop: string
  date: string
  disease: string
  confidence: string
  severity: string
  cause: string
  symptoms: string
  treatment: string
  prevention: string
  estimatedRecovery: string
  estimatedCost: string
  recoveryOutlook: string
  irrigationNotes: string
  followUp: string
  footer: string
  severityLow: string
  severityMedium: string
  severityHigh: string
}

const LABELS: Partial<Record<SupportedLanguage, PdfLabels>> & { en: PdfLabels } = {
  en: {
    reportTitle: "Crop Diagnosis Report",
    farmer: "Farmer",
    crop: "Crop",
    date: "Date",
    disease: "Disease",
    confidence: "Confidence",
    severity: "Severity",
    cause: "Cause",
    symptoms: "Symptoms",
    treatment: "Treatment plan",
    prevention: "Prevention",
    estimatedRecovery: "Estimated recovery",
    estimatedCost: "Estimated cost (₹ / INR)",
    recoveryOutlook: "Recovery outlook",
    irrigationNotes: "Irrigation notes",
    followUp: "Follow-up",
    footer:
      "Generated by AgriMind AI — Your AI Farming Partner From Seed To Harvest.",
    severityLow: "LOW",
    severityMedium: "MEDIUM",
    severityHigh: "HIGH",
  },
  hi: {
    reportTitle: "फसल रोग निदान रिपोर्ट",
    farmer: "किसान",
    crop: "फसल",
    date: "तारीख",
    disease: "रोग",
    confidence: "विश्वास",
    severity: "गंभीरता",
    cause: "कारण",
    symptoms: "लक्षण",
    treatment: "उपचार योजना",
    prevention: "रोकथाम",
    estimatedRecovery: "अनुमानित स्वस्थ होने का समय",
    estimatedCost: "अनुमानित लागत (रु.)",
    recoveryOutlook: "स्वस्थ होने की संभावना",
    irrigationNotes: "सिंचाई नोट्स",
    followUp: "अनुवर्ती",
    footer:
      "AgriMind AI द्वारा बनाई गई — बीज से फसल तक आपका AI कृषि साथी।",
    severityLow: "कम",
    severityMedium: "मध्यम",
    severityHigh: "अधिक",
  },
  mr: {
    reportTitle: "पीक रोग निदान अहवाल",
    farmer: "शेतकरी",
    crop: "पीक",
    date: "तारीख",
    disease: "रोग",
    confidence: "विश्वासार्हता",
    severity: "तीव्रता",
    cause: "कारण",
    symptoms: "लक्षणे",
    treatment: "उपचार योजना",
    prevention: "प्रतिबंधात्मक उपाय",
    estimatedRecovery: "अपेक्षित सुधारणा कालावधी",
    estimatedCost: "अंदाजे खर्च (रु.)",
    recoveryOutlook: "सुधारणेचा अंदाज",
    irrigationNotes: "सिंचन टिपा",
    followUp: "पुढील देखरेख",
    footer:
      "AgriMind AI द्वारे तयार केले — बियाण्यापासून काढणीपर्यंत तुमचा AI शेती सोबती.",
    severityLow: "कमी",
    severityMedium: "मध्यम",
    severityHigh: "जास्त",
  },
}

export function getPdfLabels(lang: SupportedLanguage): PdfLabels {
  return LABELS[lang] ?? LABELS.en
}

export function formatPdfDate(date: Date, lang: SupportedLanguage): string {
  const bcp47 = getAsianLanguage(lang)?.bcp47 ?? "en-IN"
  try {
    return date.toLocaleDateString(bcp47, {
      year: "numeric",
      month: "long",
      day: "numeric",
    })
  } catch {
    return date.toLocaleDateString("en-IN")
  }
}

export function severityLabel(
  severity: string,
  labels: PdfLabels
): string {
  const key = severity.toLowerCase()
  if (key === "low") return labels.severityLow
  if (key === "medium") return labels.severityMedium
  if (key === "high") return labels.severityHigh
  return severity.toUpperCase()
}
